"""
Task 1.3: Data Integration and Relationship Mapping (Team Member 1 - Data Engineer)

Objective: successfully join the three cleaned datasets and establish their
relationships, producing:

    1. An integrated dataset with all relevant information
       -> data/integrated/master_dataset.csv
    2. An entity-relationship diagram          -> docs/entity_relationship_diagram.md (hand-authored)
    3. A data dictionary with all fields explained -> docs/data_dictionary.md (hand-authored)
    4. Join operation documentation and validation results
       -> reports/task_1_3_data_integration_report.md (generated by this script)

Reads from data/cleaned/ (Task 1.1's output), never the raw generated files.

Run from the grid-analysis/ directory after task_1_1_data_cleaning.py:
    python tasks/task_1_3_data_integration.py
"""
import json
import os
from datetime import datetime

import pandas as pd

from report_utils import dataframe_to_markdown_table, require_files

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLEAN_DIR = os.path.join(BASE_DIR, "data", "cleaned")
INTEGRATED_DIR = os.path.join(BASE_DIR, "data", "integrated")
REPORT_PATH = os.path.join(BASE_DIR, "reports", "task_1_3_data_integration_report.md")

SUBSTATION_LOOKUP_COLS = {
    "Name": "name", "Short Name": "short_name", "Region": "region", "Country": "country",
    "Latitude": "latitude", "Longitude": "longitude", "Voltage (kV)": "voltage_kv",
    "Capacity (MVA)": "capacity_mva", "Commissioning Year": "commissioning_year",
    "Type": "type", "Status": "status",
}
UTILITY_LOOKUP_COLS = {
    "Name": "name", "Alias": "alias", "Code": "code", "Type": "type",
    "Country": "country", "Active": "active",
}


def load_clean():
    paths = [os.path.join(CLEAN_DIR, f"{name}_clean.csv")
             for name in ("utilities", "substations", "lines")]
    require_files(paths, "Run tasks/task_1_1_data_cleaning.py first "
                          "(from the grid-analysis/ directory).")
    utilities, substations, lines = (pd.read_csv(p) for p in paths)
    return utilities, substations, lines


# ---------------------------------------------------------------------------
# Step 1: handle orphaned records before joining
# ---------------------------------------------------------------------------
def find_and_handle_orphans(utilities, substations, lines):
    """Identify lines referencing a Substation ID or Utility ID that doesn't
    exist, and drop them - a line to nowhere can't be placed in the master
    dataset or the Task 2.1 graph. Returns (clean_lines, orphan_report)."""
    valid_sub_ids = set(substations["Substation ID"])
    valid_utility_ids = set(utilities["Utility ID"])

    orphan_mask = (
        ~lines["Source Substation ID"].isin(valid_sub_ids)
        | ~lines["Destination Substation ID"].isin(valid_sub_ids)
        | ~lines["Utility ID"].isin(valid_utility_ids)
    )
    orphaned = lines[orphan_mask]
    clean_lines = lines[~orphan_mask].copy()

    return clean_lines, {
        "orphaned_line_ids": orphaned["Line ID"].tolist(),
        "orphaned_count": len(orphaned),
    }


# ---------------------------------------------------------------------------
# Step 2: build the master/integrated dataset
# ---------------------------------------------------------------------------
def build_master_dataset(utilities, substations, lines):
    # add_prefix("Source ") turns "Substation ID" into "Source Substation ID",
    # which already matches lines' merge-key column name - no rename needed.
    # utilities.csv already has a column literally called "Utility ID", so
    # add_prefix("Utility ") turns it into "Utility Utility ID" and *that* one
    # does need renaming back to the merge-key name.
    substation_source = substations.add_prefix("Source ")
    substation_dest = substations.add_prefix("Destination ")
    utility_prefixed = utilities.add_prefix("Utility ").rename(
        columns={"Utility Utility ID": "Utility ID"})

    merged = lines.merge(
        substation_source, on="Source Substation ID", how="left", validate="many_to_one")
    merged = merged.merge(
        substation_dest, on="Destination Substation ID", how="left", validate="many_to_one")
    merged = merged.merge(
        utility_prefixed, on="Utility ID", how="left", validate="many_to_one")

    return merged


def validate_join(lines_before, master):
    """The join is a left join on lines, so row count must be preserved
    exactly and no row should come back with a null endpoint/utility (which
    would mean the orphan-handling step in Step 1 missed something)."""
    issues = []
    if len(master) != len(lines_before):
        issues.append(
            f"Row count changed during merge: {len(lines_before)} lines in, "
            f"{len(master)} rows out (a left join should never change row count).")

    null_source = master["Source Name"].isnull().sum()
    null_dest = master["Destination Name"].isnull().sum()
    null_utility = master["Utility Name"].isnull().sum()
    if null_source:
        issues.append(f"{null_source} rows have no matching source substation after the join.")
    if null_dest:
        issues.append(f"{null_dest} rows have no matching destination substation after the join.")
    if null_utility:
        issues.append(f"{null_utility} rows have no matching utility after the join.")

    return issues


# ---------------------------------------------------------------------------
# Step 3: lookup dictionaries
# ---------------------------------------------------------------------------
def build_substation_lookup(substations):
    # DataFrame.to_dict() has documented, version-stable native-Python-type
    # conversion (int/float/str, not numpy.int64/float64). Iterating rows with
    # .iterrows() instead would leave that conversion to pandas' internal
    # object-array construction, which is an implementation detail rather than
    # a documented guarantee - and numpy.int64 isn't natively JSON-serializable,
    # so relying on it risks a lookup that silently serialises numbers as
    # strings on a different pandas version.
    lookup_df = substations.set_index("Substation ID")[list(SUBSTATION_LOOKUP_COLS.keys())]
    lookup_df = lookup_df.rename(columns=SUBSTATION_LOOKUP_COLS)
    lookup_df.index = lookup_df.index.astype(int)
    return lookup_df.to_dict(orient="index")


def build_utility_lookup(utilities):
    lookup_df = utilities.set_index("Utility ID")[list(UTILITY_LOOKUP_COLS.keys())]
    lookup_df = lookup_df.rename(columns=UTILITY_LOOKUP_COLS)
    lookup_df.index = lookup_df.index.astype(int)
    return lookup_df.to_dict(orient="index")


def write_outputs(master, substation_lookup, utility_lookup):
    os.makedirs(INTEGRATED_DIR, exist_ok=True)
    master.to_csv(os.path.join(INTEGRATED_DIR, "master_dataset.csv"), index=False)
    with open(os.path.join(INTEGRATED_DIR, "substations_lookup.json"), "w") as f:
        json.dump(substation_lookup, f, indent=2, default=str)
    with open(os.path.join(INTEGRATED_DIR, "utilities_lookup.json"), "w") as f:
        json.dump(utility_lookup, f, indent=2, default=str)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
def write_report(utilities, substations, raw_lines, clean_lines, orphan_report, master,
                  join_issues, substation_lookup, utility_lookup):
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    out = []
    out.append("# Task 1.3 - Data Integration and Relationship Mapping Report\n")
    out.append(f"_Generated {datetime.now().isoformat(timespec='seconds')}_\n")
    out.append("_Source: `data/cleaned/*.csv` (Task 1.1 output)._\n")
    out.append("See also: [Entity-Relationship Diagram](../docs/entity_relationship_diagram.md), "
                "[Data Dictionary](../docs/data_dictionary.md).\n")

    out.append("\n## 1. Foreign-key relationships established\n")
    out.append("- `lines.Utility ID` -> `utilities.Utility ID` (many lines per utility)\n")
    out.append("- `lines.Source Substation ID` -> `substations.Substation ID` (many lines "
                "originate at one substation)\n")
    out.append("- `lines.Destination Substation ID` -> `substations.Substation ID` (many "
                "lines terminate at one substation)\n")

    out.append("\n## 2. Orphaned-record handling\n")
    out.append(f"- Raw (cleaned) line count before integration: {len(raw_lines)}\n")
    out.append(f"- Orphaned lines found (Source/Destination Substation ID or Utility ID "
                f"not present in the reference tables): {orphan_report['orphaned_count']}\n")
    if orphan_report["orphaned_line_ids"]:
        out.append(f"- Orphaned Line IDs (dropped from the master dataset): "
                    f"{orphan_report['orphaned_line_ids']}\n")
    else:
        out.append("- No orphaned lines found - every line's foreign keys resolve correctly.\n")
    out.append(f"- Line count after removing orphans (input to the join): {len(clean_lines)}\n")

    out.append("\n## 3. Join operation and validation\n")
    out.append(f"- Master dataset shape: {master.shape[0]} rows x {master.shape[1]} columns\n")
    out.append("- Join type: left join (lines as the base table), so every surviving line is "
                "guaranteed one row in the master dataset - no fan-out, no silent drops.\n")
    if join_issues:
        out.append("- **Validation issues found:**\n")
        for issue in join_issues:
            out.append(f"  - {issue}\n")
    else:
        out.append("- **Validation passed:** row count preserved exactly "
                    f"({len(clean_lines)} in, {len(master)} out) and every row has a "
                    "matching source substation, destination substation, and utility.\n")

    out.append("\n## 4. Lookup dictionaries\n")
    out.append(f"- `substations_lookup.json`: {len(substation_lookup)} entries, keyed by "
                "Substation ID.\n")
    out.append(f"- `utilities_lookup.json`: {len(utility_lookup)} entries, keyed by Utility ID.\n")
    sample_sub_id = next(iter(substation_lookup)) if substation_lookup else None
    if sample_sub_id is not None:
        out.append(f"- Example: `substations_lookup[{sample_sub_id}]` = "
                    f"`{substation_lookup[sample_sub_id]}`\n")

    out.append("\n## 5. Master dataset preview\n")
    preview_cols = ["Line ID", "Source Name", "Source Region", "Destination Name",
                     "Destination Region", "Utility Alias", "Voltage (kV)", "Length (km)"]
    out.append(dataframe_to_markdown_table(
        master[preview_cols].head(5).reset_index(drop=True), index_label="row"))

    out.append("\n\n## 6. Output\n")
    out.append("- `data/integrated/master_dataset.csv`\n")
    out.append("- `data/integrated/substations_lookup.json`\n")
    out.append("- `data/integrated/utilities_lookup.json`\n")

    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(out))


def main():
    utilities, substations, lines = load_clean()

    clean_lines, orphan_report = find_and_handle_orphans(utilities, substations, lines)
    master = build_master_dataset(utilities, substations, clean_lines)
    join_issues = validate_join(clean_lines, master)

    substation_lookup = build_substation_lookup(substations)
    utility_lookup = build_utility_lookup(utilities)

    write_outputs(master, substation_lookup, utility_lookup)
    write_report(utilities, substations, lines, clean_lines, orphan_report, master,
                 join_issues, substation_lookup, utility_lookup)

    print("Task 1.3 complete.")
    print(f"  Master dataset: {master.shape[0]} rows x {master.shape[1]} columns "
          f"-> data/integrated/master_dataset.csv")
    print(f"  Lookups written: substations ({len(substation_lookup)}), "
          f"utilities ({len(utility_lookup)})")
    print(f"  Report written to reports/task_1_3_data_integration_report.md")
    if join_issues:
        print("  WARNING: validation issues found - see the report.")


if __name__ == "__main__":
    main()
