"""
Task 1.3: Data Integration and Relationship Mapping (Team Member 1 - Data
Engineer) - OOP version.

Objective: successfully join the three cleaned datasets and establish their
relationships, producing:

    1. An integrated dataset with all relevant information
       -> data/integrated/master_dataset.csv
    2. An entity-relationship diagram          -> docs/entity_relationship_diagram.md (hand-authored)
    3. A data dictionary with all fields explained -> docs/data_dictionary.md (hand-authored)
    4. Join operation documentation and validation results
       -> reports/task_1_3_data_integration_report.md (generated by this script)

Design: OrphanHandler, DatasetIntegrator, and LookupBuilder each own one
responsibility (drop unresolvable foreign keys; build+validate the join;
serialise ID->record lookups) so each is independently testable.
IntegrationReportBuilder turns their results into markdown.
DataIntegrationPipeline is the orchestrator (the script's entry point) and
contains no data-transformation logic of its own - only wiring.

Reads from data/cleaned/ (Task 1.1's output), never the raw generated files.

Run from the grid-analysis/ directory after task_1_1_data_cleaning.py:
    python tasks/task_1_3_data_integration.py
"""
import json
import os
from datetime import datetime

import pandas as pd

from report_utils import dataframe_to_markdown_table, require_files

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLEAN_DIR = os.path.join(BASE_DIR, "data", "cleaned")
INTEGRATED_DIR = os.path.join(BASE_DIR, "data", "integrated")
REPORT_PATH = os.path.join(BASE_DIR, "reports", "task_1_3_data_integration_report.md")


class OrphanHandler:
    """Identifies and drops lines whose Source/Destination Substation ID or
    Utility ID doesn't resolve against the reference tables - a line to
    nowhere can't be placed in the master dataset or the Task 2.1 graph."""

    def __init__(self, utilities, substations, lines):
        self.utilities = utilities
        self.substations = substations
        self.lines = lines

    def find_and_drop(self):
        valid_sub_ids = set(self.substations["Substation ID"])
        valid_utility_ids = set(self.utilities["Utility ID"])

        orphan_mask = (
            ~self.lines["Source Substation ID"].isin(valid_sub_ids)
            | ~self.lines["Destination Substation ID"].isin(valid_sub_ids)
            | ~self.lines["Utility ID"].isin(valid_utility_ids)
        )
        orphaned = self.lines[orphan_mask]
        clean_lines = self.lines[~orphan_mask].copy()

        report = {
            "orphaned_line_ids": orphaned["Line ID"].tolist(),
            "orphaned_count": len(orphaned),
        }
        return clean_lines, report


class DatasetIntegrator:
    """Builds the master/integrated dataset by joining lines with both
    endpoint substations and the operating utility, then validates the join."""

    def __init__(self, utilities, substations, clean_lines):
        self.utilities = utilities
        self.substations = substations
        self.clean_lines = clean_lines
        self.master = None

    def build_master_dataset(self):
        # add_prefix("Source ") turns "Substation ID" into "Source Substation
        # ID", which already matches lines' merge-key column name - no rename
        # needed. utilities.csv already has a column literally called
        # "Utility ID", so add_prefix("Utility ") turns it into "Utility
        # Utility ID" and *that* one does need renaming back.
        substation_source = self.substations.add_prefix("Source ")
        substation_dest = self.substations.add_prefix("Destination ")
        utility_prefixed = self.utilities.add_prefix("Utility ").rename(
            columns={"Utility Utility ID": "Utility ID"})

        merged = self.clean_lines.merge(
            substation_source, on="Source Substation ID", how="left", validate="many_to_one")
        merged = merged.merge(
            substation_dest, on="Destination Substation ID", how="left", validate="many_to_one")
        merged = merged.merge(
            utility_prefixed, on="Utility ID", how="left", validate="many_to_one")

        self.master = merged
        return self.master

    def validate_join(self):
        """The join is a left join on lines, so row count must be preserved
        exactly and no row should come back with a null endpoint/utility
        (which would mean OrphanHandler missed something)."""
        if self.master is None:
            raise RuntimeError("build_master_dataset() must run before validate_join()")

        issues = []
        master, clean_lines = self.master, self.clean_lines
        if len(master) != len(clean_lines):
            issues.append(
                f"Row count changed during merge: {len(clean_lines)} lines in, "
                f"{len(master)} rows out (a left join should never change row count).")

        null_source = master["Source Name"].isnull().sum()
        null_dest = master["Destination Name"].isnull().sum()
        null_utility = master["Utility Name"].isnull().sum()
        if null_source:
            issues.append(f"{null_source} rows have no matching source substation after the join.")
        if null_dest:
            issues.append(f"{null_dest} rows have no matching destination substation after the join.")
        if null_utility:
            issues.append(f"{null_utility} rows have no matching utility after the join.")

        return issues


class LookupBuilder:
    """Serialises O(1) ID -> record lookup dictionaries for downstream reuse
    (e.g. GridCare-Lite's substation import)."""

    SUBSTATION_COLUMNS = {
        "Name": "name", "Short Name": "short_name", "Region": "region", "Country": "country",
        "Latitude": "latitude", "Longitude": "longitude", "Voltage (kV)": "voltage_kv",
        "Capacity (MVA)": "capacity_mva", "Commissioning Year": "commissioning_year",
        "Type": "type", "Status": "status",
    }
    UTILITY_COLUMNS = {
        "Name": "name", "Alias": "alias", "Code": "code", "Type": "type",
        "Country": "country", "Active": "active",
    }

    def __init__(self, substations, utilities):
        self.substations = substations
        self.utilities = utilities

    def build_substation_lookup(self):
        return self._build(self.substations, "Substation ID", self.SUBSTATION_COLUMNS)

    def build_utility_lookup(self):
        return self._build(self.utilities, "Utility ID", self.UTILITY_COLUMNS)

    @staticmethod
    def _build(df, key_column, rename_map):
        # DataFrame.to_dict() has documented, version-stable native-Python-
        # type conversion (int/float/str, not numpy.int64/float64). Iterating
        # rows with .iterrows() instead would leave that conversion to
        # pandas' internal object-array construction, which is an
        # implementation detail rather than a documented guarantee - and
        # numpy.int64 isn't natively JSON-serialisable, so relying on it
        # risks a lookup that silently serialises numbers as strings on a
        # different pandas version.
        lookup_df = df.set_index(key_column)[list(rename_map.keys())].rename(columns=rename_map)
        lookup_df.index = lookup_df.index.astype(int)
        return lookup_df.to_dict(orient="index")


class IntegrationReportBuilder:
    """Builds the Task 1.3 markdown report from the pipeline's results."""

    def __init__(self, report_path):
        self.report_path = report_path
        self._lines = []

    def _write(self, text=""):
        self._lines.append(text)

    def build(self, raw_lines, clean_lines, orphan_report, master, join_issues,
              substation_lookup, utility_lookup):
        self._write("# Task 1.3 - Data Integration and Relationship Mapping Report\n")
        self._write(f"_Generated {datetime.now().isoformat(timespec='seconds')}_\n")
        self._write("_Source: `data/cleaned/*.csv` (Task 1.1 output)._\n")
        self._write("See also: [Entity-Relationship Diagram](../docs/entity_relationship_diagram.md), "
                     "[Data Dictionary](../docs/data_dictionary.md).\n")

        self._write("\n## 1. Foreign-key relationships established\n")
        self._write("- `lines.Utility ID` -> `utilities.Utility ID` (many lines per utility)\n")
        self._write("- `lines.Source Substation ID` -> `substations.Substation ID` (many lines "
                     "originate at one substation)\n")
        self._write("- `lines.Destination Substation ID` -> `substations.Substation ID` (many "
                     "lines terminate at one substation)\n")

        self._write("\n## 2. Orphaned-record handling\n")
        self._write(f"- Raw (cleaned) line count before integration: {len(raw_lines)}\n")
        self._write(f"- Orphaned lines found (Source/Destination Substation ID or Utility ID "
                     f"not present in the reference tables): {orphan_report['orphaned_count']}\n")
        if orphan_report["orphaned_line_ids"]:
            self._write(f"- Orphaned Line IDs (dropped from the master dataset): "
                         f"{orphan_report['orphaned_line_ids']}\n")
        else:
            self._write("- No orphaned lines found - every line's foreign keys resolve correctly.\n")
        self._write(f"- Line count after removing orphans (input to the join): {len(clean_lines)}\n")

        self._write("\n## 3. Join operation and validation\n")
        self._write(f"- Master dataset shape: {master.shape[0]} rows x {master.shape[1]} columns\n")
        self._write("- Join type: left join (lines as the base table), so every surviving line is "
                     "guaranteed one row in the master dataset - no fan-out, no silent drops.\n")
        if join_issues:
            self._write("- **Validation issues found:**\n")
            for issue in join_issues:
                self._write(f"  - {issue}\n")
        else:
            self._write("- **Validation passed:** row count preserved exactly "
                         f"({len(clean_lines)} in, {len(master)} out) and every row has a "
                         "matching source substation, destination substation, and utility.\n")

        self._write("\n## 4. Lookup dictionaries\n")
        self._write(f"- `substations_lookup.json`: {len(substation_lookup)} entries, keyed by "
                     "Substation ID.\n")
        self._write(f"- `utilities_lookup.json`: {len(utility_lookup)} entries, keyed by Utility ID.\n")
        sample_sub_id = next(iter(substation_lookup)) if substation_lookup else None
        if sample_sub_id is not None:
            self._write(f"- Example: `substations_lookup[{sample_sub_id}]` = "
                         f"`{substation_lookup[sample_sub_id]}`\n")

        self._write("\n## 5. Master dataset preview\n")
        preview_cols = ["Line ID", "Source Name", "Source Region", "Destination Name",
                         "Destination Region", "Utility Alias", "Voltage (kV)", "Length (km)"]
        self._write(dataframe_to_markdown_table(
            master[preview_cols].head(5).reset_index(drop=True), index_label="row"))

        self._write("\n\n## 6. Output\n")
        self._write("- `data/integrated/master_dataset.csv`\n")
        self._write("- `data/integrated/substations_lookup.json`\n")
        self._write("- `data/integrated/utilities_lookup.json`\n")

        return self

    def write(self):
        os.makedirs(os.path.dirname(self.report_path), exist_ok=True)
        with open(self.report_path, "w") as f:
            f.write("\n".join(self._lines))


class DataIntegrationPipeline:
    """Task 1.3 orchestrator - the script's entry point. Composes
    OrphanHandler, DatasetIntegrator, LookupBuilder, and
    IntegrationReportBuilder; contains no cleaning/joining logic itself."""

    def __init__(self, clean_dir=CLEAN_DIR, integrated_dir=INTEGRATED_DIR, report_path=REPORT_PATH):
        self.clean_dir = clean_dir
        self.integrated_dir = integrated_dir
        self.report_path = report_path

    def load_clean(self):
        paths = [os.path.join(self.clean_dir, f"{name}_clean.csv")
                  for name in ("utilities", "substations", "lines")]
        require_files(paths, "Run tasks/task_1_1_data_cleaning.py first "
                              "(from the grid-analysis/ directory).")
        utilities, substations, lines = (pd.read_csv(p) for p in paths)
        return utilities, substations, lines

    def run(self):
        utilities, substations, lines = self.load_clean()

        clean_lines, orphan_report = OrphanHandler(utilities, substations, lines).find_and_drop()

        integrator = DatasetIntegrator(utilities, substations, clean_lines)
        master = integrator.build_master_dataset()
        join_issues = integrator.validate_join()

        lookup_builder = LookupBuilder(substations, utilities)
        substation_lookup = lookup_builder.build_substation_lookup()
        utility_lookup = lookup_builder.build_utility_lookup()

        self._write_outputs(master, substation_lookup, utility_lookup)
        IntegrationReportBuilder(self.report_path).build(
            lines, clean_lines, orphan_report, master, join_issues,
            substation_lookup, utility_lookup).write()

        return master, substation_lookup, utility_lookup, join_issues

    def _write_outputs(self, master, substation_lookup, utility_lookup):
        os.makedirs(self.integrated_dir, exist_ok=True)
        master.to_csv(os.path.join(self.integrated_dir, "master_dataset.csv"), index=False)
        with open(os.path.join(self.integrated_dir, "substations_lookup.json"), "w") as f:
            json.dump(substation_lookup, f, indent=2, default=str)
        with open(os.path.join(self.integrated_dir, "utilities_lookup.json"), "w") as f:
            json.dump(utility_lookup, f, indent=2, default=str)


def main():
    pipeline = DataIntegrationPipeline()
    master, substation_lookup, utility_lookup, join_issues = pipeline.run()

    print("Task 1.3 complete.")
    print(f"  Master dataset: {master.shape[0]} rows x {master.shape[1]} columns "
          f"-> data/integrated/master_dataset.csv")
    print(f"  Lookups written: substations ({len(substation_lookup)}), "
          f"utilities ({len(utility_lookup)})")
    print("  Report written to reports/task_1_3_data_integration_report.md")
    if join_issues:
        print("  WARNING: validation issues found - see the report.")


if __name__ == "__main__":
    main()
