"""
Domain models for GridCare-Lite.

Each class wraps one database table and owns both its data (via __init__)
and its behaviour (state transitions, validation, queries) as methods -
the GUI in app.py never writes raw SQL; it only calls these methods. Every
class defines __str__ so an instance is readable wherever it's printed or
placed in a Tkinter widget, the same pattern as a simple appliance class:
attributes describe what it *is*, methods describe what it *does*.
"""
import csv

import bcrypt


class User:
    """A GridCare-Lite account: administrator, engineer, technician, or
    customer-service representative."""

    VALID_ROLES = ("admin", "engineer", "technician", "customer_service")

    def __init__(self, user_id, username, role, password_hash=None):
        self.user_id = user_id
        self.username = username
        self.role = role
        self.password_hash = password_hash

    def __str__(self):
        return f"User(id={self.user_id}, username={self.username}, role={self.role})"

    def check_password(self, password):
        if self.password_hash is None:
            return False
        return bcrypt.checkpw(password.encode("utf-8"), self.password_hash.encode("utf-8"))

    @staticmethod
    def hash_password(password):
        return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")

    @classmethod
    def create(cls, conn, username, password, role):
        if role not in cls.VALID_ROLES:
            raise ValueError(f"Invalid role '{role}'. Must be one of {cls.VALID_ROLES}.")
        password_hash = cls.hash_password(password)
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
            (username, password_hash, role),
        )
        conn.commit()
        return cls(cur.lastrowid, username, role, password_hash)

    @classmethod
    def find_by_username(cls, conn, username):
        cur = conn.cursor()
        cur.execute(
            "SELECT user_id, username, role, password_hash FROM users WHERE username = ?",
            (username,),
        )
        row = cur.fetchone()
        return cls(*row) if row else None

    @classmethod
    def authenticate(cls, conn, username, password):
        """Returns the matching User if the password is correct, else None."""
        cur = conn.cursor()
        cur.execute(
            "SELECT user_id, username, role, password_hash FROM users WHERE username = ?",
            (username,),
        )
        row = cur.fetchone()
        if row is None:
            return None
        user = cls(*row)
        return user if user.check_password(password) else None

    @classmethod
    def find_by_role(cls, conn, role):
        cur = conn.cursor()
        cur.execute("SELECT user_id, username, role FROM users WHERE role = ?", (role,))
        return [cls(*row) for row in cur.fetchall()]


class Substation:
    """A minimal reference record for a substation an outage can be logged
    against - imported from the grid-analysis component's cleaned data."""

    def __init__(self, substation_id, name, region):
        self.substation_id = substation_id
        self.name = name
        self.region = region

    def __str__(self):
        return f"{self.name} ({self.region})"

    @classmethod
    def all(cls, conn):
        cur = conn.cursor()
        cur.execute("SELECT substation_id, name, region FROM substations ORDER BY name")
        return [cls(*row) for row in cur.fetchall()]

    @classmethod
    def regions(cls, conn):
        """Distinct regions, for the dashboard's region filter."""
        cur = conn.cursor()
        cur.execute("SELECT DISTINCT region FROM substations ORDER BY region")
        return [row[0] for row in cur.fetchall()]

    @classmethod
    def exists(cls, conn, substation_id):
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM substations WHERE substation_id = ?", (substation_id,))
        return cur.fetchone() is not None

    @classmethod
    def import_from_csv(cls, conn, csv_path):
        """Import substation reference data generated by
        grid-analysis/generate_dataset.py (or Task 1.1's cleaned output),
        so outages can only be logged against a real substation."""
        with open(csv_path, newline="") as f:
            reader = csv.DictReader(f)
            rows = [(row["Substation ID"], row["Name"], row["Region"]) for row in reader]
        cur = conn.cursor()
        cur.executemany(
            "INSERT OR IGNORE INTO substations (substation_id, name, region) VALUES (?, ?, ?)",
            rows,
        )
        conn.commit()
        return len(rows)


class Outage:
    """A reported fault or outage at a substation, moving through
    Open -> In Progress -> Resolved."""

    VALID_STATUSES = ("Open", "In Progress", "Resolved")
    VALID_SEVERITIES = ("Low", "Medium", "High", "Critical")
    OPEN_STATUSES = ("Open", "In Progress")

    def __init__(self, outage_id, substation_id, reported_by, description,
                 severity="Medium", status="Open", reported_at=None, resolved_at=None,
                 substation_name=None, substation_region=None):
        self.outage_id = outage_id
        self.substation_id = substation_id
        self.reported_by = reported_by
        self.description = description
        self.severity = severity
        self.status = status
        self.reported_at = reported_at
        self.resolved_at = resolved_at
        self.substation_name = substation_name  # denormalised, for display only
        self.substation_region = substation_region  # denormalised, for display/filtering only

    def __str__(self):
        where = self.substation_name or f"substation #{self.substation_id}"
        return f"Outage #{self.outage_id} [{self.status}] at {where}"

    @classmethod
    def report(cls, conn, substation_id, reported_by, description, severity="Medium"):
        if not description or not description.strip():
            raise ValueError("Description is required.")
        if severity not in cls.VALID_SEVERITIES:
            raise ValueError(f"Invalid severity '{severity}'. Must be one of {cls.VALID_SEVERITIES}.")
        if not Substation.exists(conn, substation_id):
            raise ValueError(f"Substation #{substation_id} does not exist.")

        description = description.strip()
        cur = conn.cursor()
        cur.execute(
            "SELECT outage_id FROM outages WHERE substation_id = ? AND description = ? "
            "AND status IN ('Open', 'In Progress')",
            (substation_id, description),
        )
        duplicate = cur.fetchone()
        if duplicate is not None:
            raise ValueError(
                f"Outage #{duplicate[0]} with this exact description is already open at "
                f"this substation. Update the existing outage instead of logging a duplicate.")

        cur.execute(
            "INSERT INTO outages (substation_id, reported_by, description, severity) "
            "VALUES (?, ?, ?, ?)",
            (substation_id, reported_by, description, severity),
        )
        conn.commit()
        return cls(cur.lastrowid, substation_id, reported_by, description, severity)

    @classmethod
    def _from_joined_row(cls, row):
        (outage_id, substation_id, reported_by, description, severity, status,
         reported_at, resolved_at, substation_name, substation_region) = row
        return cls(outage_id, substation_id, reported_by, description, severity, status,
                    reported_at, resolved_at, substation_name, substation_region)

    @classmethod
    def all(cls, conn):
        cur = conn.cursor()
        cur.execute("""
            SELECT o.outage_id, o.substation_id, o.reported_by, o.description, o.severity,
                   o.status, o.reported_at, o.resolved_at, s.name, s.region
            FROM outages o
            LEFT JOIN substations s ON o.substation_id = s.substation_id
            ORDER BY o.reported_at DESC, o.outage_id DESC
        """)
        return [cls._from_joined_row(row) for row in cur.fetchall()]

    @classmethod
    def search(cls, conn, region=None, status=None):
        """Outages filtered by region and/or status - both optional, both
        applied as an exact match. Used by the dashboard's filter controls."""
        query = """
            SELECT o.outage_id, o.substation_id, o.reported_by, o.description, o.severity,
                   o.status, o.reported_at, o.resolved_at, s.name, s.region
            FROM outages o
            LEFT JOIN substations s ON o.substation_id = s.substation_id
            WHERE 1=1
        """
        params = []
        if region:
            query += " AND s.region = ?"
            params.append(region)
        if status:
            query += " AND o.status = ?"
            params.append(status)
        query += " ORDER BY o.reported_at DESC, o.outage_id DESC"
        cur = conn.cursor()
        cur.execute(query, params)
        return [cls._from_joined_row(row) for row in cur.fetchall()]

    @classmethod
    def open_outages(cls, conn):
        cur = conn.cursor()
        cur.execute("""
            SELECT o.outage_id, o.substation_id, o.reported_by, o.description, o.severity,
                   o.status, o.reported_at, o.resolved_at, s.name, s.region
            FROM outages o
            LEFT JOIN substations s ON o.substation_id = s.substation_id
            WHERE o.status = 'Open'
        """)
        return [cls._from_joined_row(row) for row in cur.fetchall()]

    def mark_in_progress(self, conn):
        self._set_status(conn, "In Progress")

    def mark_resolved(self, conn):
        cur = conn.cursor()
        cur.execute(
            "UPDATE outages SET status = 'Resolved', resolved_at = CURRENT_TIMESTAMP "
            "WHERE outage_id = ?",
            (self.outage_id,),
        )
        conn.commit()
        self.status = "Resolved"

    def _set_status(self, conn, status):
        if status not in self.VALID_STATUSES:
            raise ValueError(f"Invalid status '{status}'. Must be one of {self.VALID_STATUSES}.")
        cur = conn.cursor()
        cur.execute("UPDATE outages SET status = ? WHERE outage_id = ?", (status, self.outage_id))
        conn.commit()
        self.status = status


class WorkOrder:
    """A technician assignment and schedule for resolving an outage."""

    VALID_STATUSES = ("Pending", "Scheduled", "Completed")

    def __init__(self, work_order_id, outage_id, assigned_technician, scheduled_date,
                 status="Pending", outage_description=None):
        self.work_order_id = work_order_id
        self.outage_id = outage_id
        self.assigned_technician = assigned_technician
        self.scheduled_date = scheduled_date
        self.status = status
        self.outage_description = outage_description  # denormalised, for display only

    def __str__(self):
        return f"WorkOrder #{self.work_order_id} [{self.status}] for outage #{self.outage_id}"

    @classmethod
    def assign(cls, conn, outage_id, technician_id, scheduled_date):
        """Assigning a work order also moves the outage to 'In Progress' -
        an outage under an active work order should never still read 'Open'."""
        if not scheduled_date or not scheduled_date.strip():
            raise ValueError("Scheduled date is required.")
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO work_orders (outage_id, assigned_technician, scheduled_date, status) "
            "VALUES (?, ?, ?, 'Scheduled')",
            (outage_id, technician_id, scheduled_date.strip()),
        )
        cur.execute("UPDATE outages SET status = 'In Progress' WHERE outage_id = ?", (outage_id,))
        conn.commit()
        return cls(cur.lastrowid, outage_id, technician_id, scheduled_date.strip(), "Scheduled")

    @classmethod
    def for_technician(cls, conn, technician_id):
        cur = conn.cursor()
        cur.execute("""
            SELECT w.work_order_id, w.outage_id, w.assigned_technician, w.scheduled_date,
                   w.status, o.description
            FROM work_orders w
            JOIN outages o ON w.outage_id = o.outage_id
            WHERE w.assigned_technician = ?
            ORDER BY w.scheduled_date
        """, (technician_id,))
        return [cls(*row) for row in cur.fetchall()]

    def mark_complete(self, conn):
        """Completing the work order also resolves its outage."""
        cur = conn.cursor()
        cur.execute(
            "UPDATE work_orders SET status = 'Completed' WHERE work_order_id = ?",
            (self.work_order_id,),
        )
        cur.execute(
            "UPDATE outages SET status = 'Resolved', resolved_at = CURRENT_TIMESTAMP "
            "WHERE outage_id = ?",
            (self.outage_id,),
        )
        conn.commit()
        self.status = "Completed"


class Complaint:
    """A customer complaint, optionally linked to a known outage."""

    def __init__(self, complaint_id, outage_id, logged_by, customer_name, description,
                 logged_at=None, logged_by_username=None):
        self.complaint_id = complaint_id
        self.outage_id = outage_id
        self.logged_by = logged_by
        self.customer_name = customer_name
        self.description = description
        self.logged_at = logged_at
        self.logged_by_username = logged_by_username  # denormalised, for display only

    def __str__(self):
        linked = f" (linked to outage #{self.outage_id})" if self.outage_id else ""
        return f"Complaint from {self.customer_name}{linked}"

    @classmethod
    def log(cls, conn, logged_by, customer_name, description, outage_id=None):
        if not customer_name or not customer_name.strip():
            raise ValueError("Customer name is required.")
        if not description or not description.strip():
            raise ValueError("Description is required.")
        if outage_id is not None:
            cur = conn.cursor()
            cur.execute("SELECT 1 FROM outages WHERE outage_id = ?", (outage_id,))
            if cur.fetchone() is None:
                raise ValueError(f"Outage #{outage_id} does not exist.")
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO complaints (outage_id, logged_by, customer_name, description) "
            "VALUES (?, ?, ?, ?)",
            (outage_id, logged_by, customer_name.strip(), description.strip()),
        )
        conn.commit()
        return cls(cur.lastrowid, outage_id, logged_by, customer_name.strip(), description.strip())

    @classmethod
    def all(cls, conn):
        cur = conn.cursor()
        cur.execute("""
            SELECT c.complaint_id, c.outage_id, c.logged_by, c.customer_name, c.description,
                   c.logged_at, u.username
            FROM complaints c
            LEFT JOIN users u ON c.logged_by = u.user_id
            ORDER BY c.logged_at DESC, c.complaint_id DESC
        """)
        return [cls(*row) for row in cur.fetchall()]


class Report:
    """Read-only aggregate queries for the operational Reports screen -
    never mutates data, only summarises what Outage/WorkOrder/Complaint
    have already recorded."""

    @staticmethod
    def status_counts(conn):
        """{'Open': n, 'In Progress': n, 'Resolved': n} - zero-filled so the
        screen doesn't have to special-case a status with no rows yet."""
        counts = {status: 0 for status in Outage.VALID_STATUSES}
        cur = conn.cursor()
        cur.execute("SELECT status, COUNT(*) FROM outages GROUP BY status")
        counts.update(dict(cur.fetchall()))
        return counts

    @staticmethod
    def severity_counts(conn):
        counts = {severity: 0 for severity in Outage.VALID_SEVERITIES}
        cur = conn.cursor()
        cur.execute("SELECT severity, COUNT(*) FROM outages GROUP BY severity")
        counts.update(dict(cur.fetchall()))
        return counts

    @staticmethod
    def outages_by_region(conn):
        """[(region, count), ...] sorted by count descending. Substations
        with no region on record (shouldn't happen, but the join is LEFT)
        are grouped under 'Unknown'."""
        cur = conn.cursor()
        cur.execute("""
            SELECT COALESCE(s.region, 'Unknown') AS region, COUNT(*)
            FROM outages o
            LEFT JOIN substations s ON o.substation_id = s.substation_id
            GROUP BY region
            ORDER BY COUNT(*) DESC
        """)
        return cur.fetchall()

    @staticmethod
    def average_resolution_hours(conn):
        """Average hours between reported_at and resolved_at for resolved
        outages, or None if nothing has been resolved yet. SQLite has no
        native datetime-diff operator, so this uses julianday() (days since
        a fixed epoch, fractional) and converts the difference to hours."""
        cur = conn.cursor()
        cur.execute("""
            SELECT AVG((julianday(resolved_at) - julianday(reported_at)) * 24.0)
            FROM outages
            WHERE status = 'Resolved' AND resolved_at IS NOT NULL
        """)
        result = cur.fetchone()[0]
        return round(result, 1) if result is not None else None

    @staticmethod
    def summary(conn):
        """Everything the Reports screen needs, in one call."""
        return {
            "status_counts": Report.status_counts(conn),
            "severity_counts": Report.severity_counts(conn),
            "by_region": Report.outages_by_region(conn),
            "avg_resolution_hours": Report.average_resolution_hours(conn),
            "total_outages": sum(Report.status_counts(conn).values()),
            "total_complaints": len(Complaint.all(conn)),
        }
